using GestaoDeEquipamentos.ConsoleApp.Compartilhado;

namespace GestaoDeEquipamentos.ConsoleApp.ModuloFabricante;

public class RepositorioFabricanteEmMemoria : RepositorioBaseEmMemoria<Fabricante>, IRepositorioFabricante;