using GestaoDeEquipamentos.ConsoleApp.Compartilhado;

namespace GestaoDeEquipamentos.ConsoleApp.ModuloEquipamento;

public class RepositorioEquipamentoEmMemoria : RepositorioBaseEmMemoria<Equipamento>, IRepositorioEquipamento;